version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_game
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: juegodb
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: root
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_game
    restart: always
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres

volumes:
  postgres-data:
